Set `CONDA_BUILD_SYSROOT` on Travis CI
Configures the `CONDA_BUILD_SYSROOT` to based on where the macOS SDKs
are on Travis CI. As this is dynamically determined by inspection on
Travis CI at run time, add it to `conda-forge-ci-setup` for the macOS
builds.

diff --git a/recipe/run_conda_forge_build_setup_osx b/recipe/run_conda_forge_build_setup_osx
--- a/recipe/run_conda_forge_build_setup_osx
+++ b/recipe/run_conda_forge_build_setup_osx
@@ -12,6 +12,16 @@ export PYTHONUNBUFFERED=1
 #   way is working well enough.
 export MACOSX_DEPLOYMENT_TARGET="10.9"
 
+export CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
+
+if [ -f "${CONDA_BUILD_SYSROOT}" ]
+then
+    echo "Found CONDA_BUILD_SYSROOT: ${CONDA_BUILD_SYSROOT}"
+else
+    echo "Missing CONDA_BUILD_SYSROOT: ${CONDA_BUILD_SYSROOT}"
+    exit 1
+fi
+
 conda config --set show_channel_urls true
 conda config --set auto_update_conda false
 conda config --set add_pip_as_python_dependency false
